### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by manur** [rhaker/react-native-select-contact-phone-ios#1]
Hello,

I'd be interested in using this module, if Android support will be upcoming in the near future. I'm new to React Native, and I'm developing an app on both major platforms.

Any chance this is planned? Thanks in advance.

**Comment by rhaker** [comment]
I'm guessing that someone will be developing an android module that has this functionality (given how fast the community is evolving). If no one has developed something by the time I get to building on Android, I'm going to build something - although I can't promise when this will be.
