### ISSUE TITLE
ABAddressBook Framework deprecated in iOS 9

### ISSUE THREAD

**Issue by davidsims9t** [rhaker/react-native-select-contact-phone-ios#3]
It looks like the ABAdressBook in iOS 9 is deprecated. Do you have any plans on switching over to the Contact Framework? https://developer.apple.com/library/prerelease/ios/documentation/Contacts/Reference/Contacts_Framework/index.html#//apple_ref/doc/uid/TP40015328

Great plugin! Thanks!

**Comment by rhaker** [comment]
Thanks. I noted in the readme under Known Issues that the framework needs to be updated. I'm going to update as soon as I have the time, but there are a bunch of other things that I want to do first. All the best...
