### ISSUE TITLE
How can I get Names and Number

### ISSUE THREAD

**Issue by AdamBrodzinski** [rhaker/react-native-select-contact-phone-ios#5]
I see that you have multiple projects to get either or, but how can i have them press the name and return the name and number?

Also if there's no way to do this do you know of any other libs that do this (natively, the js ones are too slow).

**Comment by rhaker** [comment]
Thanks for trying this module out. The short answer is these modules won't give you 1 click with both name and number being returned.  You can try one of the following though:

1) Use the name or number module to get a value, then use react-native-contacts or react-native-addressbook to query the value against all the contacts. I haven't tried this (and haven't used those other modules). I think they give you all the contacts in the addressbook. So, it's basically a two-step process. First get one value via the click, then query the contacts in javascript for the second value. In theory it should work. There may be issues, though.

2) It's a terrible user experience, but you have the two click option.

3) Fork the code.

Good luck.

**Comment by AdamBrodzinski** [comment]
Thanks for the info. I'm currently using react-native-contacts but it's taking 10 seconds on some peoples phones (and others is fast). I wish I could fork but I don't know any Obj-C yet. 

Cheers

**Comment by rhaker** [comment]
I have faith that you can do it. It's not too hard. 

1) import the select contact name module using npm
2) open up the RNSelectContactName.m file in your editor
3) go to RNSelectContactPhone.m file in my github repo
4) copy lines 108 through 116 from RNSelectContactPhone.m to RNSelectContactName.m (the code should be pasted right before line 108 in RNSelectContactName.m)
5) In RNSelectContactName.m, add the following after @"lastName" : returnLastName,

@"phoneNumber" : phoneNumber,

6) In your javascript, add value.phoneNumber to your callback.
7) Save everything, recompile, clean and build.
8) You did it.

**Comment by AdamBrodzinski** [comment]
@rhaker hey thanks! I'll give this a try :+1:
